spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Eshopping
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}